version: 0.1.0.{build}
install:
  - ps: iwr https://raw.githubusercontent.com/dotnet/cli/release/2.1.3xx/scripts/obtain/dotnet-install.ps1 -outfile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300-preview2-008530 -InstallDir $env:ProgramFiles/dotnet
branches:
  only:
    - master
    - appveyor
    - /^feature\/.*/
build_script:
  - ps: .\build.ps1 -IsOfficialBuild
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    name: myget
    artifact: Packages
    server: https://www.myget.org/F/git-status-cli/api/v2/package
    symbol_server: https://www.myget.org/F/git-status-cli/api/v2/package
    api_key:
      secure: fD3Ct3DYJC7z1MGJvgvslATD9ZfF44PwTwOIaNWqPUU/hx4vjV6SL2XuFR39AKJn